language: php 

compiler:
  - gcc
  - clang

os:
  - linux

php:
  - 7.1
  - 7.2
  - 7.3

notifications:
  email: bob_zy@yeah.net

install:
   - composer install
  
before_script:
    - phpize && ./configure && make && make install
    - echo "extension = phptars.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
    - cd testcases 
    - phpunit test.php
    - phpunit testTARSClient.php
    - phpunit testTARSServer.php


